global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  # API Spring Boot rodando no host (fora do Docker)
  - job_name: challenge-ford
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          app: car-search-api
