ALTER TABLE veiculos
    ADD COLUMN criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN anonimizado TINYINT(1) NOT NULL DEFAULT 0;

ALTER TABLE veiculo_especificacoes
    MODIFY COLUMN nome VARCHAR(80) NOT NULL,
    MODIFY COLUMN valor VARCHAR(255) NOT NULL;

ALTER TABLE veiculos
    MODIFY COLUMN marca VARCHAR(80) NOT NULL,
    MODIFY COLUMN modelo VARCHAR(80) NOT NULL,
    MODIFY COLUMN versao VARCHAR(80) NOT NULL;
